import type { Metadata } from "next";
import { Almarai } from "@next/font/google";
import "./globals.css";
import {Footer} from './components/footer';
import { Header } from "./components/header";
import 'swiper/css';
import 'swiper/css/navigation';
import 'swiper/css/pagination';


// إعداد الخط
const almarai = Almarai({
  subsets: ["arabic"],
  weight: ["400", "700"],
  variable: "--font-almarai",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ar" className={almarai.variable} dir="rtl">
      <body className="min-h-screen flex flex-col">
        <Header />
          <main className="flex-1">
            {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
